import {
  PayCircleOutlined,
  ShoppingCartOutlined,
  MessageOutlined,
  TeamOutlined,
  UserOutlined,
  DashboardOutlined,
  ApiOutlined,
  CameraOutlined,
  EditOutlined,
  CodeOutlined,
  LineOutlined,
  BarChartOutlined,
  AreaChartOutlined,
  FallOutlined,
  RiseOutlined,
  BorderInnerOutlined,
  ToolOutlined,
  AuditOutlined,
  CalendarOutlined,
  DollarOutlined,
  CalculatorOutlined,
  RightOutlined,
} from '@ant-design/icons'

export default {
  'rightButton': <RightOutlined />,
  'pay-circle-o': <PayCircleOutlined />,
  'shopping-cart': <ShoppingCartOutlined />,
  'camera-o': <CameraOutlined />,
  'line-chart': <LineOutlined />,
  'code-o': <CodeOutlined />,
  'area-chart': <AreaChartOutlined />,
  'bar-chart': <BarChartOutlined />,
  'up-trend': <RiseOutlined />,
  'down-trend': <FallOutlined />,
  'panel': <BorderInnerOutlined />,
  'tool': <ToolOutlined />,
  'audit': <AuditOutlined />,
  'calendar': <CalendarOutlined />,
  'dollar': <DollarOutlined />,
  'calc': <CalculatorOutlined />,
  message: <MessageOutlined />,
  team: <TeamOutlined />,
  dashboard: <DashboardOutlined />,
  user: <UserOutlined />,
  api: <ApiOutlined />,
  edit: <EditOutlined />,
}
